### ISSUE TITLE
Any Idea how to use in GitHub Codespaces?

### ISSUE THREAD

**Issue by bilalbox** [siemens/packetflix#8]
Thanks for making such a powerful tool! I can't tell you how excited I got when I came across [Edgeshark](https://github.com/siemens/edgeshark) 🤯 😂 

I've already been using this tool to great effect in learning and teaching basic BGP configuration on various containerized NOSes, but I did run into one small hitch when trying to use it in [GitHub Codespaces](https://github.com/features/codespaces). 

## The Problem:
In GitHub Codespaces, Edgeshark launches fine, but when attempting to attach to the `packetflix...` URI created when clicking the little fin icon, I get an error like the following:

```
Error from extcap pipe: time="2024-07-05T03:39:19+08:00" level=error msg="cannot decode targets from GhostWire-on-Packetflix service: invalid character '<' looking for beginning of value"
time="2024-07-05T03:39:19+08:00" level=error msg="cannot contact capture service via websocket: websocket: bad handshake"
time="2024-07-05T03:39:19+08:00" level=error msg="cannot start capture: websocket: bad handshake"
time="2024-07-05T03:39:19+08:00" level=error msg="finished with status code 1"
```

Here's an example packetflix URI for the Edgeshark running in my codespace:
```
packetflix:wss://musical-disco-v6ggg9v4qvx2xv6x-5001.app.github.dev/capture?container=%7B%22netns%22%3A4026532277%2C%22network-interfaces%22%3A%5B%22swp1%22%5D%2C%22name%22%3A%22clab-protect-x2%22%2C%22type%22%3A%22docker%22%2C%22prefix%22%3A%22%22%7D&nif=swp1
```

I have a feeling tweaking that packetflix URI slightly might make it reachable even behind all the NATs and LBs and whatnot exposing my services in the codespace, but I'm not really sure where to start. Any ideas?

## Desired Outcome:
I was hoping that clicking the fin icon would trigger a successful capture in Wireshark as it does when I run Edgeshark on my own servers or a local VM.

## Steps to Reproduce:
0. Make sure to have [Wireshark](https://www.wireshark.org/download.html) and the [Extcap Plugin](https://github.com/siemens/cshargextcap) installed
1. Launch [a new codespace for the bgplabs repo](https://github.com/codespaces/new?hide_repo_select=true&ref=master&repo=674097176)
2. Start one of the labs, such as [basics/6-protect](https://bgplabs.net/basic/6-protect/) by navigating into the directory and running `netlab up`
3. Launch Edgeshark with their docker-compose script:
```bash
wget -q --no-cache -O - \
  https://github.com/siemens/edgeshark/raw/main/deployments/wget/docker-compose-localhost.yaml \
  | docker compose -f - up
```
4. Click the "launch in browser" pop-up presenting in the codespace Web UI after it detects the new Edgeshark web service running
5. Click the refresh icon in the Edgeshark UI to expose all the new containers with their vNICs
6. Click the fin icon to start a capture on one of the vNICs
7. Click `Open Wireshark` button in the packetflix handler pop-up to launch Wireshark
8. See the above-mentioned error displayed.

Thanks for your support!

**Comment by thediveo** [comment]
According to Roman Dodin capture should also work (but I unfortunately don't have the resources to check this myself).

The first error message might give a clue, as the Wireshark cshargextcap plugin internally does a two-phase communication with the packetflix service: the cryptic error message (which I haven't found yet a way to improve the reporting) indicates that the plugin cannot successfully complete the first phase https REST API call in order to confirm the capture target information.

Something in-between is responding with an https error response body, when the packetflix REST API endpoint should respond with JSON.

Unfortunately, I don't have yet any idea where things break...

**Comment by thediveo** [comment]
If you set an environment variable `CSHARK_LOG` to a path and filename in a way that this envvar gets passed into Wireshark and then the capture plugin, then the plugin will write debug information. In particular, it will write in which phase things failed.

Based on https://docs.github.com/en/codespaces/developing-in-a-codespace/forwarding-ports-in-your-codespace#using-command-line-tools-and-rest-clients-to-access-ports maybe you can access via a localhost port forwarding using native vscode; make sure to access Edgeshark's web ui then via localhost, as this carries over into the packetflix URL.

I've noticed mention of an X-GITHUB-TOKEN header ... that could be supported in the extcap's config dialog, but I'm yet not clear if this would be useful or instead rather a pain.

**Comment by bilalbox** [comment]
> If you set an environment variable `CSHARK_LOG` to a path and filename in a way that this envvar gets passed into Wireshark and then the capture plugin, then the plugin will write debug information. In particular, it will write in which phase things failed.
> 
> Based on https://docs.github.com/en/codespaces/developing-in-a-codespace/forwarding-ports-in-your-codespace#using-command-line-tools-and-rest-clients-to-access-ports maybe you can access via a localhost port forwarding using native vscode; make sure to access Edgeshark's web ui then via localhost, as this carries over into the packetflix URL.
> 
> I've noticed mention of an X-GITHUB-TOKEN header ... that could be supported in the extcap's config dialog, but I'm yet not clear if this would be useful or instead rather a pain.

Aha, so I guess trying to connect to the exposed 5001 port on the remote codespace doesn't work because it actually has to use a combination of TLS on port 443 and the embedding the TCP port 5001 into the FQDN that isn't easy to use with that cshargextcap plugin. 

But hey, I've got good news! Accessing the codespace via local VSCode totally did the trick, as I can now access Edgeshark (and use Wireshark) on localhost:5001. This is a very slick solution!

Thanks for your support and prompt response.

**Comment by thediveo** [comment]
That's something for the documentation to have, thank you for reporting!
